[project]
name = "homelab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinfra>=3.5.1",
    # from ansible requirements.txt
    "ansible==10.0.1",
    "jmespath==1.0.1",
    "netaddr==1.3.0",
    "dnspython==2.6.1",
    "passlib==1.7.4",
    "ansible-lint>=25.11.0",
    "black>=25.11.0",
]
