- name: _test | Install podman
  import_role:
    name: _test
    tasks_from: podman

- name: _test | Trigger podman ip (TODO proper solution)
  command: podman run -ti --rm ubuntu whoami
  become: true
