- name: Add profilarr group
  group:
    name: profilarr
    system: true
  become: true
  tags:
    - profilarr
    - _check_stage1
    - _check_stage2

- name: Add profilarr user
  user:
    name: profilarr
    group: profilarr
    createhome: false
    system: true
    shell: /usr/sbin/nologin
    home: /nonexistent
  become: true
  register: profilarr_user
  tags:
    - profilarr
    - _check_stage1
    - _check_stage2

- name: Create configuration directory
  when: not (ansible_check_mode and profilarr_user.changed)
  file:
    dest: /mnt/services/profilarr
    state: directory
    owner: profilarr
    group: profilarr
    mode: "0755"
  become: true
  tags:
    - profilarr
    - _check_stage2

# - name: Configure profilarr
#   template:
#     src: config.xml.j2
#     dest: /mnt/services/profilarr/config.xml
#     owner: profilarr
#     group: profilarr
#     mode: "0600"
#     backup: true
#   register: profilarr_conf
#   become: true
#   tags:
#     - profilarr
#     - _check_stage2

- name: Install profilarr service
  import_role:
    name: systemd_unit
    tasks_from: template
  vars:
    systemd_unit_src: profilarr.service
    systemd_unit_condition: "{{ not (ansible_check_mode and profilarr_user.changed) }}"
  tags:
    - profilarr
    - _check_stage2

- name: Enable profilarr service
  import_role:
    name: systemd_unit
    tasks_from: service
  vars:
    systemd_unit_src: profilarr
    systemd_unit_condition: "{{ not (ansible_check_mode and (systemd_unit.changed or profilarr_user.changed)) }}"
    systemd_unit_restart: "{{ systemd_unit.changed }}"
  tags:
    - profilarr

- name: Configure nginx
  import_role:
    name: nginx
    tasks_from: site
  vars:
    nginx_subdomain: profilarr
    nginx_proxy_pass: http://localhost:6868/
  tags:
    - profilarr
