zfs_root: false
home_subnet: 10.0.2.0/24
macvlan_parent: enp0s3
grub_bootloader: true
netplan:
  ethernets:
    enp0s3:
      link-local: [] # do not setup random link local address when no dhcp is present
      wakeonlan: true
      dhcp4: true
      dhcp6: false
