zfs_root: true
zfs_has_services_mount: false
zfs_has_scratch_mount: false
zfs_has_media_mount: false
zfs_has_data_mount: false
zfs_has_minio_mount: false
home_subnet: 10.0.2.0/24
macvlan_parent: enp0s2
grub_bootloader: false
netplan:
  ethernets:
    enp0s2:
      link-local: [] # do not setup random link local address when no dhcp is present
      wakeonlan: true
      dhcp4: true
      dhcp6: false
